service:
  name: sample-sls-cognito
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    USERPOOLID:
      Ref: CognitoUserPool
    USERPOOL_CLIENTID:
      Ref: CognitoUserPoolClient
  region: ap-northeast-1

resources:
  # Cognito
  - ${file(serverless/cognito-user-pool.yml)}
  # Api Gateway Authorizer
  - ${file(serverless/apigateway-authorizer.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  signUp:
    handler: src/signUp.signUp
    events:
      - http:
          method: post
          path: signUp
  confirmSignUp:
    handler: src/confirmSignUp.confirmSignUp
    events:
      - http:
          method: post
          path: confirmSignUp
  resend:
    handler: src/resend.resend
    events:
      - http:
          method: post
          path: resend
  refresh:
    handler: src/refresh.refresh
    events:
      - http:
          method: post
          path: refresh
